# 데이터 분석 기초
---

## 일반적인 데이터 과학 단계
> 데이터 수집 -> 데이터 준비 -> 데이터 탐색 -> 데이터 모델링 -> 시각화, 자동화

### 1. 데이터 수집 - raw data
#### 크롤링
- SNS, 웹 정보 등 인터넷에서 제공하는 데이터 수집
- 웹 추출 데이터

#### Open API
- 개방된 API를 이용하여 서비스나 데이터 자유롭게 사용
- 공공데이터 포탈 등

### 2. 데이터 준비
: raw data를 적절한 형태로 정제, 가공

### 3. 데이터 탐색
: 데이터와 변수간의 상관 관계나 상호 작용 이해를 위한 단계로 변수 간의 관련성, 데이터의 분포, 편차, 패턴 등을 알아본다.

### 4. 데이터 모델링
: 탐색한 데이터의 특성과 목적에 따라 모델을 선택한다

#### 데이터 분석 모델의 종류
- 통계 분석 모델 : 주로 수치형 데이터에 사용, 확률 기반 현상 추정 및 예측
    - 기술 통계 : 평균, 중앙값, 최빈값, 분산 등
    - 상관 분석 : 두 개의 변수가 가진 선형적 관계 분석
    - 회귀 분석 
        - 독립변수와 종속변수간의 상호 연관성 정도를 파악하기 위한 분석기법
        - 변수 간의 인과관계 분석에 자주 사용
    - 분산분석
    - 주성분 분석
- 데이터 마이닝 모델 : 패턴인식, AI, 머신러닝, 딥러닝 등에 사용
    - 예측
    - 분류
    - 군집화
    - 패턴 분석
    
---

# 머신러닝
- 경험을 통해 학습하는 것을 컴퓨터가 수행할 수 있도록 가르치는 데이터 분석 기법. 
- 머신 러닝 알고리즘은 미리 결정된 방정식을 모델로 의존하지 않고 계산 방법을 사용하여 데이터에서 직접 정보를 학습한다.

## 머신러닝은 언제 사용하는가?
: 대용량 데이터, 다량의 변수가 있으나 기존의 공식이나 방정식이 없는 복잡한 작업들
- 얼굴 인식, 음성 인식 : 직접 규칙과 방정식을 작성하기에는 너무 복잡하다
- 신용카드 회사에서 예측되지 않은 사용 발견 ( 사기 검출 ) : 작업 규칙이 지속적으로 바뀌는 경우
- 수요 예측, 추세 예측 등 데이터 특징이 계속 바뀌고 그에 따라 프로그램 조정이 필요 시

## 머신러닝 작동 방식
### 지도 학습 - 분류, 회귀
: 정답이 존재하는 데이터를 활용한 학습
### 비지도 학습 - 군집화
: 정답이 존재하지 않는 데이터 활용한 학습. 데이터에서 숨겨진 패턴이나 형태 찾기
### 강화 학습

![image.png](attachment:image.png)

---

# numpy
## numpy 배열 생성
- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.arange()`

In [4]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
type(a)

In [ ]:
np.zeros(2)

In [ ]:
np.ones(2)

In [ ]:
np.arange(4)

In [ ]:
np.arange(2, 9, 2)

In [ ]:
np.ones(2, dtype=np.int64)

---
## 요소 추가, 제거, 정렬
- `np.sort()`
- `np.concatenate()`

In [5]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0) # axis = 0이면 행, 1이면 열 의미

array([[1, 2],
       [3, 4],
       [5, 6]])

---
## 배열의 모양, 크기
- `ndarray.ndim`
- `ndarray.size`
- `ndarray.shape`

In [ ]:
arr = np.array([[[0, 1, 2, 3],
                [4, 5, 6, 7]],

                [[0, 1, 2, 3],
                [4, 5, 6, 7]],

                [[0 ,1 ,2, 3],
                [4, 5, 6, 7]]])

print('배열의 차원 수 :',arr.ndim)
print('배열의 총 요소 수 :',arr.size)
print('배열의 모양(차원, 행, 열) :',arr.shape)

---
## 배열 재구성
- `ndarray.reshape()` : 변경하려는 배열의 모습이 원본 배열과 동일한 수의 요소를 가져야한다.

In [7]:
a = np.arange(6)
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


---
## 인덱싱, 슬라이싱
파이썬 리스트와 동일하게 numpy 배열 인덱싱, 슬라이싱

### 특정 조건을 충족하는 값을 배열에서 선택하기

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('a[a < 5] :', a[a < 5])

five_up = (a >= 5)
print('a[five_up] :', a[five_up])

divBy2 = a[a%2==0]
print('divBy2 :', divBy2)

c = a[(a > 2) & (a < 11)]
print('& 또는 | 연산 :',c)

# bool 값 반환
print(a>5)

---
## 배열 연산
- 더하기, 빼기, 곱하기, 나누기
- `max()`, `min()`, `sum()`

In [8]:
list1 = [1,2,3]
list2 = [1,2,3]
print(list1 + list2)

data = np.array([1, 2])
ones = np.ones(2, dtype=int) # 데이터 타입 일치시키기
print(data + ones)
print(data - ones)
print(data * data)
print(data / data)
print(data * 1.5)

[1, 2, 3, 1, 2, 3]
[2 3]
[0 1]
[1 4]
[1. 1.]
[1.5 3. ]


In [ ]:
a = np.array([1, 2, 3, 4])

print(a.sum())

b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0)) # 행 축 합산
print(b.sum(axis=1)) # 열 축 합산

---
## 행렬 생성과 연산
2차원 배열 생성

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data[0, 1])  # 행렬[행, 열]
print(data[1:3])
print(data[0:2, 0])

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data.max(axis=0)

In [ ]:
data.max(axis=1)

---
# Pandas
: 데이터 조작 및 분석을 위한 라이브러리

## Pandas 데이터 구조
- Series : 1차원 배열
- DataFrame : 2차원 배열

## 객체 생성

In [9]:
import pandas as pd
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -0.433358
b    0.450619
c    1.076445
d   -1.388125
e    0.063686
dtype: float64

In [ ]:
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}
df = pd.DataFrame(d)
df

In [ ]:
df = pd.DataFrame(d, index=["a", "b", "c", "d"])
df

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
dates = pd.date_range("20220101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

---
## 데이터 보기
- `head()`
- `tail()`
- `describe()` : 데이터의 통계 요약 출력
- `sort_index` : 축으로 정렬
- `sort_values` : 값으로 정렬